title: Dog life
author: Maruyus
email: my-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  It's the best ever!!!!

# social links
twitter_username: elonmusk # DO NOT include the @ character, or else the build will fail!
github_username:  Maruyus # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
